package com.it.bean;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTENT_TYPE.
 * 内容分类对象
 */
public class ContentType {

	@SerializedName("id")
    private Long id;
	@SerializedName("name")
    private String name;
	@SerializedName("type")
    private Integer type;

    public ContentType() {
    }

    public ContentType(Long id) {
        this.id = id;
    }

    public ContentType(Long id, String name, Integer type) {
        this.id = id;
        this.name = name;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
