package com.it.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.it.bean.ContentInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CONTENT_INFO.
*/
public class ContentInfoDao extends AbstractDao<ContentInfo, Long> {

    public static final String TABLENAME = "CONTENT_INFO";

    /**
     * Properties of entity ContentInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Content_data = new Property(1, String.class, "content_data", false, "CONTENT_DATA");
        public final static Property Content_type = new Property(2, Integer.class, "content_type", false, "CONTENT_TYPE");
        public final static Property Content_classify_name = new Property(3, String.class, "content_classify_name", false, "CONTENT_CLASSIFY_NAME");
        public final static Property Is_valid = new Property(4, Integer.class, "is_valid", false, "IS_VALID");
        public final static Property Is_hot = new Property(5, String.class, "is_hot", false, "IS_HOT");
        public final static Property Insert_time = new Property(6, java.util.Date.class, "insert_time", false, "INSERT_TIME");
    };


    public ContentInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ContentInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CONTENT_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CONTENT_DATA' TEXT," + // 1: content_data
                "'CONTENT_TYPE' INTEGER," + // 2: content_type
                "'CONTENT_CLASSIFY_NAME' TEXT," + // 3: content_classify_name
                "'IS_VALID' INTEGER," + // 4: is_valid
                "'IS_HOT' TEXT," + // 5: is_hot
                "'INSERT_TIME' INTEGER);"); // 6: insert_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CONTENT_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ContentInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String content_data = entity.getContent_data();
        if (content_data != null) {
            stmt.bindString(2, content_data);
        }
 
        Integer content_type = entity.getContent_type();
        if (content_type != null) {
            stmt.bindLong(3, content_type);
        }
 
        String content_classify_name = entity.getContent_classify_name();
        if (content_classify_name != null) {
            stmt.bindString(4, content_classify_name);
        }
 
        Integer is_valid = entity.getIs_valid();
        if (is_valid != null) {
            stmt.bindLong(5, is_valid);
        }
 
        String is_hot = entity.getIs_hot();
        if (is_hot != null) {
            stmt.bindString(6, is_hot);
        }
 
        java.util.Date insert_time = entity.getInsert_time();
        if (insert_time != null) {
            stmt.bindLong(7, insert_time.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ContentInfo readEntity(Cursor cursor, int offset) {
        ContentInfo entity = new ContentInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // content_data
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // content_type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // content_classify_name
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // is_valid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // is_hot
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // insert_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ContentInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContent_data(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent_type(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setContent_classify_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIs_valid(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setIs_hot(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setInsert_time(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ContentInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ContentInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
