package com.it.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.it.bean.UserInfo;
import com.it.bean.ContentInfo;
import com.it.bean.ContentType;

import com.it.bean.UserInfoDao;
import com.it.bean.ContentInfoDao;
import com.it.bean.ContentTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig contentInfoDaoConfig;
    private final DaoConfig contentTypeDaoConfig;

    private final UserInfoDao userInfoDao;
    private final ContentInfoDao contentInfoDao;
    private final ContentTypeDao contentTypeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        contentInfoDaoConfig = daoConfigMap.get(ContentInfoDao.class).clone();
        contentInfoDaoConfig.initIdentityScope(type);

        contentTypeDaoConfig = daoConfigMap.get(ContentTypeDao.class).clone();
        contentTypeDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        contentInfoDao = new ContentInfoDao(contentInfoDaoConfig, this);
        contentTypeDao = new ContentTypeDao(contentTypeDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(ContentInfo.class, contentInfoDao);
        registerDao(ContentType.class, contentTypeDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        contentInfoDaoConfig.getIdentityScope().clear();
        contentTypeDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ContentInfoDao getContentInfoDao() {
        return contentInfoDao;
    }

    public ContentTypeDao getContentTypeDao() {
        return contentTypeDao;
    }

}
