package com.it.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_APPRAISAL_TREASURE.
 */
public class MyAppraisalTreasure {

    private Long id;
    private Integer treasure_id;
    private Integer treasure_owner_id;
    private Integer appraiser_id;
    private Integer appraisal_result;
    private String appraisal_data;
    private Integer is_valid;
    private Integer is_appraisal_completed;
    private java.util.Date insert_time;

    public MyAppraisalTreasure() {
    }

    public MyAppraisalTreasure(Long id) {
        this.id = id;
    }

    public MyAppraisalTreasure(Long id, Integer treasure_id, Integer treasure_owner_id, Integer appraiser_id, Integer appraisal_result, String appraisal_data, Integer is_valid, Integer is_appraisal_completed, java.util.Date insert_time) {
        this.id = id;
        this.treasure_id = treasure_id;
        this.treasure_owner_id = treasure_owner_id;
        this.appraiser_id = appraiser_id;
        this.appraisal_result = appraisal_result;
        this.appraisal_data = appraisal_data;
        this.is_valid = is_valid;
        this.is_appraisal_completed = is_appraisal_completed;
        this.insert_time = insert_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTreasure_id() {
        return treasure_id;
    }

    public void setTreasure_id(Integer treasure_id) {
        this.treasure_id = treasure_id;
    }

    public Integer getTreasure_owner_id() {
        return treasure_owner_id;
    }

    public void setTreasure_owner_id(Integer treasure_owner_id) {
        this.treasure_owner_id = treasure_owner_id;
    }

    public Integer getAppraiser_id() {
        return appraiser_id;
    }

    public void setAppraiser_id(Integer appraiser_id) {
        this.appraiser_id = appraiser_id;
    }

    public Integer getAppraisal_result() {
        return appraisal_result;
    }

    public void setAppraisal_result(Integer appraisal_result) {
        this.appraisal_result = appraisal_result;
    }

    public String getAppraisal_data() {
        return appraisal_data;
    }

    public void setAppraisal_data(String appraisal_data) {
        this.appraisal_data = appraisal_data;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public Integer getIs_appraisal_completed() {
        return is_appraisal_completed;
    }

    public void setIs_appraisal_completed(Integer is_appraisal_completed) {
        this.is_appraisal_completed = is_appraisal_completed;
    }

    public java.util.Date getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(java.util.Date insert_time) {
        this.insert_time = insert_time;
    }

}
