package com.it.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_COLLECT_CONTENT.
 */
public class MyCollectContent {

    private Long id;
    private Integer user_id;
    private Integer content_id;
    private Integer is_valid;
    private java.util.Date insert_time;

    public MyCollectContent() {
    }

    public MyCollectContent(Long id) {
        this.id = id;
    }

    public MyCollectContent(Long id, Integer user_id, Integer content_id, Integer is_valid, java.util.Date insert_time) {
        this.id = id;
        this.user_id = user_id;
        this.content_id = content_id;
        this.is_valid = is_valid;
        this.insert_time = insert_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getContent_id() {
        return content_id;
    }

    public void setContent_id(Integer content_id) {
        this.content_id = content_id;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public java.util.Date getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(java.util.Date insert_time) {
        this.insert_time = insert_time;
    }

}
