package com.it.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.it.bean.RTreasureComment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RTREASURE_COMMENT.
*/
public class RTreasureCommentDao extends AbstractDao<RTreasureComment, Long> {

    public static final String TABLENAME = "RTREASURE_COMMENT";

    /**
     * Properties of entity RTreasureComment.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, Integer.class, "user_id", false, "USER_ID");
        public final static Property Treasure_id = new Property(2, Integer.class, "treasure_id", false, "TREASURE_ID");
        public final static Property To_user_id = new Property(3, Integer.class, "to_user_id", false, "TO_USER_ID");
        public final static Property Comment_data = new Property(4, String.class, "comment_data", false, "COMMENT_DATA");
        public final static Property Is_checked = new Property(5, Integer.class, "is_checked", false, "IS_CHECKED");
        public final static Property Is_valid = new Property(6, Integer.class, "is_valid", false, "IS_VALID");
        public final static Property Insert_time = new Property(7, java.util.Date.class, "insert_time", false, "INSERT_TIME");
    };


    public RTreasureCommentDao(DaoConfig config) {
        super(config);
    }
    
    public RTreasureCommentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RTREASURE_COMMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'USER_ID' INTEGER," + // 1: user_id
                "'TREASURE_ID' INTEGER," + // 2: treasure_id
                "'TO_USER_ID' INTEGER," + // 3: to_user_id
                "'COMMENT_DATA' TEXT," + // 4: comment_data
                "'IS_CHECKED' INTEGER," + // 5: is_checked
                "'IS_VALID' INTEGER," + // 6: is_valid
                "'INSERT_TIME' INTEGER);"); // 7: insert_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RTREASURE_COMMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RTreasureComment entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(2, user_id);
        }
 
        Integer treasure_id = entity.getTreasure_id();
        if (treasure_id != null) {
            stmt.bindLong(3, treasure_id);
        }
 
        Integer to_user_id = entity.getTo_user_id();
        if (to_user_id != null) {
            stmt.bindLong(4, to_user_id);
        }
 
        String comment_data = entity.getComment_data();
        if (comment_data != null) {
            stmt.bindString(5, comment_data);
        }
 
        Integer is_checked = entity.getIs_checked();
        if (is_checked != null) {
            stmt.bindLong(6, is_checked);
        }
 
        Integer is_valid = entity.getIs_valid();
        if (is_valid != null) {
            stmt.bindLong(7, is_valid);
        }
 
        java.util.Date insert_time = entity.getInsert_time();
        if (insert_time != null) {
            stmt.bindLong(8, insert_time.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RTreasureComment readEntity(Cursor cursor, int offset) {
        RTreasureComment entity = new RTreasureComment( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // treasure_id
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // to_user_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // comment_data
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // is_checked
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // is_valid
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)) // insert_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RTreasureComment entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setTreasure_id(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setTo_user_id(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setComment_data(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIs_checked(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setIs_valid(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setInsert_time(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RTreasureComment entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RTreasureComment entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
