package com.it.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TREASURE_TYPE.
 * 宝物分类
 */
public class TreasureType {

	public static final int TYPE_FIRST = 0;//第一层
	public static final int TYPE_SECOND = 1;//第二层
	public static final int TYPE_THIRD = 2;//第三层
	
    private Long id; 
    private Long currnt_id; //宝物id
    private String name;//宝物名字
    private Integer type;//宝物级别
    private Long parent_id;//父类id

    public TreasureType() {
    }

    public TreasureType(Long id) {
        this.id = id;
    }

    public TreasureType(Long id, Long currnt_id, String name, Integer type, Long parent_id) {
        this.id = id;
        this.currnt_id = currnt_id;
        this.name = name;
        this.type = type;
        this.parent_id = parent_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCurrnt_id() {
        return currnt_id;
    }

    public void setCurrnt_id(Long currnt_id) {
        this.currnt_id = currnt_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getParent_id() {
        return parent_id;
    }

    public void setParent_id(Long parent_id) {
        this.parent_id = parent_id;
    }

}
