package com.it.bean;

import com.google.gson.annotations.SerializedName;
import com.lidroid.xutils.db.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo {

	public String getSession_id() {
		return session_id;
	}

	public void setSession_id(String session_id) {
		this.session_id = session_id;
	}

	@SerializedName("id")
	private Long id;
	
	
	@SerializedName("nickname")
	private String nickname;
	
	@SerializedName("password")
	private String password;
	
	@SerializedName("mobile")
	private String mobile;
	
	@SerializedName("portrait")
	private String portrait;
	
	@SerializedName("user_type")
	private Integer user_type;
	
	@SerializedName("user_level")
	private Integer user_level;
	
	@SerializedName("personal_data")
	private String personal_data;
	
	@SerializedName("is_valid")
	private Integer is_valid;
	@SerializedName("is_famous_expert")
	private Integer is_famous_expert;

	
	@Unique
	@SerializedName("session_id")
	private String session_id;


	@SerializedName("insert_time")
    private Long insert_time;
	@SerializedName("is_system")
    private Boolean is_system;
    @SerializedName("is_bind")
    private Boolean is_bind;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, String nickname, String password, String mobile, String portrait, Integer user_type, Integer user_level, String personal_data, Integer is_valid, Integer is_famous_expert, Long insert_time, Boolean is_system, Boolean is_bind) {
        this.id = id;
        this.nickname = nickname;
        this.password = password;
        this.mobile = mobile;
        this.portrait = portrait;
        this.user_type = user_type;
        this.user_level = user_level;
        this.personal_data = personal_data;
        this.is_valid = is_valid;
        this.is_famous_expert = is_famous_expert;
        this.insert_time = insert_time;
        this.is_system = is_system;
        this.is_bind = is_bind;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPortrait() {
        return portrait;
    }

    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    public Integer getUser_type() {
        return user_type;
    }

    public void setUser_type(Integer user_type) {
        this.user_type = user_type;
    }

    public Integer getUser_level() {
        return user_level;
    }

    public void setUser_level(Integer user_level) {
        this.user_level = user_level;
    }

    public String getPersonal_data() {
        return personal_data;
    }

    public void setPersonal_data(String personal_data) {
        this.personal_data = personal_data;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public Integer getIs_famous_expert() {
        return is_famous_expert;
    }

    public void setIs_famous_expert(Integer is_famous_expert) {
        this.is_famous_expert = is_famous_expert;
    }

    public Long getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(Long insert_time) {
        this.insert_time = insert_time;
    }

    public Boolean getIs_system() {
        return is_system;
    }

    public void setIs_system(Boolean is_system) {
        this.is_system = is_system;
    }

    public Boolean getIs_bind() {
        return is_bind;
    }

    public void setIs_bind(Boolean is_bind) {
        this.is_bind = is_bind;
    }

}
