package com.yingluo.Appraiser.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yingluo.Appraiser.bean.ContentInfo;
import com.yingluo.Appraiser.bean.ContentInfoDao;
import com.yingluo.Appraiser.bean.TreasureType;
import com.yingluo.Appraiser.bean.TreasureTypeDao;
import com.yingluo.Appraiser.bean.UserInfo;
import com.yingluo.Appraiser.bean.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig contentInfoDaoConfig;
    private final DaoConfig treasureTypeDaoConfig;

    private final UserInfoDao userInfoDao;
    private final ContentInfoDao contentInfoDao;
    private final TreasureTypeDao treasureTypeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        contentInfoDaoConfig = daoConfigMap.get(ContentInfoDao.class).clone();
        contentInfoDaoConfig.initIdentityScope(type);

        treasureTypeDaoConfig = daoConfigMap.get(TreasureTypeDao.class).clone();
        treasureTypeDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        contentInfoDao = new ContentInfoDao(contentInfoDaoConfig, this);
        treasureTypeDao = new TreasureTypeDao(treasureTypeDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(ContentInfo.class, contentInfoDao);
        registerDao(TreasureType.class, treasureTypeDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        contentInfoDaoConfig.getIdentityScope().clear();
        treasureTypeDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ContentInfoDao getContentInfoDao() {
        return contentInfoDao;
    }

    public TreasureTypeDao getTreasureTypeDao() {
        return treasureTypeDao;
    }

}
