package com.yingluo.Appraiser.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IM_USER_INFO.
 */
public class ImUserInfo {

    private Long id;
    private String name;
    private String icon;

    public ImUserInfo() {
    }

    public ImUserInfo(Long id) {
        this.id = id;
    }

    public ImUserInfo(Long id, String name, String icon) {
        this.id = id;
        this.name = name;
        this.icon = icon;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}
