package com.yingluo.Appraiser.bean;

import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYSTEM_INFO_ENTITY.
 */
public class SystemInfoEntity {

    public Long id;
    public String mobile;
    
	@SerializedName("treasure_id")
	public long treasure_id;
	
	@SerializedName("content")
	public String content;
	
	@SerializedName("time")
	public String time;

    public SystemInfoEntity() {
    }

    public SystemInfoEntity(Long id) {
        this.id = id;
    }

    public SystemInfoEntity(Long id, String mobile, String time, String content, Long treasure_id) {
        this.id = id;
        this.mobile = mobile;
        this.time = time;
        this.content = content;
        this.treasure_id = treasure_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getTreasure_id() {
        return treasure_id;
    }

    public void setTreasure_id(Long treasure_id) {
        this.treasure_id = treasure_id;
    }

}
