package com.it.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_SYSTEM_NOTICE.
 */
public class MySystemNotice {

    private Long id;
    private Integer user_id;
    private String notice_data;
    private Integer notice_type;
    private Integer is_read;
    private Integer is_valid;
    private java.util.Date insert_time;

    public MySystemNotice() {
    }

    public MySystemNotice(Long id) {
        this.id = id;
    }

    public MySystemNotice(Long id, Integer user_id, String notice_data, Integer notice_type, Integer is_read, Integer is_valid, java.util.Date insert_time) {
        this.id = id;
        this.user_id = user_id;
        this.notice_data = notice_data;
        this.notice_type = notice_type;
        this.is_read = is_read;
        this.is_valid = is_valid;
        this.insert_time = insert_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getNotice_data() {
        return notice_data;
    }

    public void setNotice_data(String notice_data) {
        this.notice_data = notice_data;
    }

    public Integer getNotice_type() {
        return notice_type;
    }

    public void setNotice_type(Integer notice_type) {
        this.notice_type = notice_type;
    }

    public Integer getIs_read() {
        return is_read;
    }

    public void setIs_read(Integer is_read) {
        this.is_read = is_read;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public java.util.Date getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(java.util.Date insert_time) {
        this.insert_time = insert_time;
    }

}
