package com.it.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MY_TREASURE.
 */
public class MyTreasure {

    private Long id;
    private String user_id;
    private String treasure_description;
    private String treasure_all_view_data;
    private String treasure_special_view_data;
    private Integer treasure_level;
    private String treasure_classify;
    private Integer is_appraisal;
    private Integer is_special;
    private Integer is_valid;
    private java.util.Date insert_time;

    public MyTreasure() {
    }

    public MyTreasure(Long id) {
        this.id = id;
    }

    public MyTreasure(Long id, String user_id, String treasure_description, String treasure_all_view_data, String treasure_special_view_data, Integer treasure_level, String treasure_classify, Integer is_appraisal, Integer is_special, Integer is_valid, java.util.Date insert_time) {
        this.id = id;
        this.user_id = user_id;
        this.treasure_description = treasure_description;
        this.treasure_all_view_data = treasure_all_view_data;
        this.treasure_special_view_data = treasure_special_view_data;
        this.treasure_level = treasure_level;
        this.treasure_classify = treasure_classify;
        this.is_appraisal = is_appraisal;
        this.is_special = is_special;
        this.is_valid = is_valid;
        this.insert_time = insert_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getTreasure_description() {
        return treasure_description;
    }

    public void setTreasure_description(String treasure_description) {
        this.treasure_description = treasure_description;
    }

    public String getTreasure_all_view_data() {
        return treasure_all_view_data;
    }

    public void setTreasure_all_view_data(String treasure_all_view_data) {
        this.treasure_all_view_data = treasure_all_view_data;
    }

    public String getTreasure_special_view_data() {
        return treasure_special_view_data;
    }

    public void setTreasure_special_view_data(String treasure_special_view_data) {
        this.treasure_special_view_data = treasure_special_view_data;
    }

    public Integer getTreasure_level() {
        return treasure_level;
    }

    public void setTreasure_level(Integer treasure_level) {
        this.treasure_level = treasure_level;
    }

    public String getTreasure_classify() {
        return treasure_classify;
    }

    public void setTreasure_classify(String treasure_classify) {
        this.treasure_classify = treasure_classify;
    }

    public Integer getIs_appraisal() {
        return is_appraisal;
    }

    public void setIs_appraisal(Integer is_appraisal) {
        this.is_appraisal = is_appraisal;
    }

    public Integer getIs_special() {
        return is_special;
    }

    public void setIs_special(Integer is_special) {
        this.is_special = is_special;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public java.util.Date getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(java.util.Date insert_time) {
        this.insert_time = insert_time;
    }

}
