package com.it.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RTREASURE_COMMENT.
 */
public class RTreasureComment {

    private Long id;
    private Integer user_id;
    private Integer treasure_id;
    private Integer to_user_id;
    private String comment_data;
    private Integer is_checked;
    private Integer is_valid;
    private java.util.Date insert_time;

    public RTreasureComment() {
    }

    public RTreasureComment(Long id) {
        this.id = id;
    }

    public RTreasureComment(Long id, Integer user_id, Integer treasure_id, Integer to_user_id, String comment_data, Integer is_checked, Integer is_valid, java.util.Date insert_time) {
        this.id = id;
        this.user_id = user_id;
        this.treasure_id = treasure_id;
        this.to_user_id = to_user_id;
        this.comment_data = comment_data;
        this.is_checked = is_checked;
        this.is_valid = is_valid;
        this.insert_time = insert_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getTreasure_id() {
        return treasure_id;
    }

    public void setTreasure_id(Integer treasure_id) {
        this.treasure_id = treasure_id;
    }

    public Integer getTo_user_id() {
        return to_user_id;
    }

    public void setTo_user_id(Integer to_user_id) {
        this.to_user_id = to_user_id;
    }

    public String getComment_data() {
        return comment_data;
    }

    public void setComment_data(String comment_data) {
        this.comment_data = comment_data;
    }

    public Integer getIs_checked() {
        return is_checked;
    }

    public void setIs_checked(Integer is_checked) {
        this.is_checked = is_checked;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public java.util.Date getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(java.util.Date insert_time) {
        this.insert_time = insert_time;
    }

}
