package com.it.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUGGESTION_INFO.
 */
public class SuggestionInfo {

    private Long id;
    private String user_id;
    private String suggestion;
    private Integer is_valid;
    private java.util.Date insert_time;

    public SuggestionInfo() {
    }

    public SuggestionInfo(Long id) {
        this.id = id;
    }

    public SuggestionInfo(Long id, String user_id, String suggestion, Integer is_valid, java.util.Date insert_time) {
        this.id = id;
        this.user_id = user_id;
        this.suggestion = suggestion;
        this.is_valid = is_valid;
        this.insert_time = insert_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getSuggestion() {
        return suggestion;
    }

    public void setSuggestion(String suggestion) {
        this.suggestion = suggestion;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public java.util.Date getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(java.util.Date insert_time) {
        this.insert_time = insert_time;
    }

}
