package com.it.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TREASURE_MATERIAL_CLASSIFY.
 */
public class TreasureMaterialClassify {

    private Long id;
    private String classify_name;
    private Integer current_level;
    private Integer parent_id;
    private String classify_path;
    private Integer is_valid;
    private java.util.Date insert_time;

    public TreasureMaterialClassify() {
    }

    public TreasureMaterialClassify(Long id) {
        this.id = id;
    }

    public TreasureMaterialClassify(Long id, String classify_name, Integer current_level, Integer parent_id, String classify_path, Integer is_valid, java.util.Date insert_time) {
        this.id = id;
        this.classify_name = classify_name;
        this.current_level = current_level;
        this.parent_id = parent_id;
        this.classify_path = classify_path;
        this.is_valid = is_valid;
        this.insert_time = insert_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClassify_name() {
        return classify_name;
    }

    public void setClassify_name(String classify_name) {
        this.classify_name = classify_name;
    }

    public Integer getCurrent_level() {
        return current_level;
    }

    public void setCurrent_level(Integer current_level) {
        this.current_level = current_level;
    }

    public Integer getParent_id() {
        return parent_id;
    }

    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    public String getClassify_path() {
        return classify_path;
    }

    public void setClassify_path(String classify_path) {
        this.classify_path = classify_path;
    }

    public Integer getIs_valid() {
        return is_valid;
    }

    public void setIs_valid(Integer is_valid) {
        this.is_valid = is_valid;
    }

    public java.util.Date getInsert_time() {
        return insert_time;
    }

    public void setInsert_time(java.util.Date insert_time) {
        this.insert_time = insert_time;
    }

}
